### ISSUE TITLE
I have a few questions about Gait3D-Benchmark Datasets

### ISSUE THREAD

**Issue by jjunnii** [Gait3D/Gait3D-Benchmark#10]
Hi. Im jjun.
I read your paper impressively.

We don't currently live in China, so it is difficult to use dataset on baidu disk. 

If you don't mind, is there a way to download the dataset to another disk (e.g Google drive)?

**Comment by JinkaiZheng** [comment]
Hi, @jjunnii. We are so sorry that we don't have any other disk at present. 
But we will upload it to Onedrive later, and we will inform you at that time, thank you for your understanding!

**Comment by jjunnii** [comment]
Thank you for your response. I have one more question. I'm going to conduct an experiment with my custom dataset, but it's hard to understand the data structure, so what kind of information do you have on the /lib/modeling/models/smplgait.py. line41
![image](https://user-images.githubusercontent.com/76198695/189056488-bd3a41a2-f661-4ed7-99a3-d3301927bb8a.png)
What data does seql have here? Is the sequence length per identity? Specifically, I wonder what kind of data structure seql has.

**Comment by JinkaiZheng** [comment]
Hi, **seqL** is a list of the lengths of each sequence used during the test phase.
Because we load all frames at test time, and each sequence length is different.

**Comment by jjunnii** [comment]
Thank you very much. Lastly, should I set seql to None during the training time? Impressed and the current study under way into your paper. Your advice is likely to be a great help.

**Comment by JinkaiZheng** [comment]
Yes, seqL can be set to None. Because the training process doesn't use it. We fix the length of each sequence for stable training.

**Comment by jjunnii** [comment]
Thank you. Your reply was very helpful.
