### ISSUE TITLE
Question about 3D SMPL skeleton topology diagram

### ISSUE THREAD

**Issue by HL-HYX** [Gait3D/Gait3D-Benchmark#11]
Your work promotes the application of gait recognition in real scenes, can you provide the topology diagram of the SMPL 3D skeleton in Gait3D? Because the specific meaning of the 24 joint points is not stated in your data description document.

**Comment by JinkaiZheng** [comment]
Hi~ I'm so sorry. Our poor consideration indeed causes this. 
The following image is what you want.

![dc4f04733e45940e4b6aa86b0ebd6634](https://user-images.githubusercontent.com/39995121/190098556-2311f19b-c174-4441-93fa-60fc19db7526.png)

**Comment by HL-HYX** [comment]
Thank you very much for your reply!

**Comment by HL-HYX** [comment]
![image](https://user-images.githubusercontent.com/43193663/190411747-46902537-b21f-4bb7-a589-afa7da88f31e.png)

**Comment by HL-HYX** [comment]
Hello, sorry to bother you again!
Just I have another question: In your ReadMe.txt, there are two types of data framed by the red box in the figure below. From a visualization of your data, I found that j3d_smpl24(24, 3) describes the 3D coordinates of the nodes. **_So what does pose(72, ) mean?_**
![image](https://user-images.githubusercontent.com/43193663/190413647-29522d42-1df0-41cb-84a1-4c548ec565a9.png)

**Comment by JinkaiZheng** [comment]
Yes, _j3d_smpl24 (24, 3)_ means the 3D keypoints coordinate and _pose (72, )_ equals 24*3, specifically, is the rotation (axial angle) of each joint around the X/Y/Z axis in the above figure.
