### ISSUE TITLE
About data generation

### ISSUE THREAD

**Issue by yan811** [Gait3D/Gait3D-Benchmark#12]
Hi! I 'd like to know some details about data generation in NPZ files.

In npz file:
1 What's the order of "pose"? SMPL pose parameter should be [24,3] dim, how did you convert it to [72,]? The order is [keypoint1_angel1, keypoint1_angle2,  keypoint1_angle3,  keypoint2_angel1, keypoint2_angle2,  keypoint2_angle3...] or [keypoint1_angle1, keypoint2_angle1... keypoint1_angle2, keypoint2_angle2... keypoint1_angle3, keypoint1_angle3... ] ?

2 How did you generate pose into SMPL format,SPIN format , and OpenPose format? 
   What's the order of the second dim?
   Is the keypoint order the same with SMPL model?

3 In pkl file:
For example, dim of data in './0000/camid0_videoid2/seq0/seq0.pkl' is [48,85]. What's the order  of dim 1? Is it ordered by time order or shuffled?

**Comment by JinkaiZheng** [comment]
Hi~ Thanks for your questions.
1. The order of pose is [72, ], and you can convert it to [24, 3]. The specific order can be referred to [here](https://github.com/Gait3D/Gait3D-Benchmark/issues/11#issuecomment-1246404561)
2. We generate pose by [ROMP](https://github.com/Arthur151/ROMP). You can look for the generation process from it.
3. [Here](https://github.com/Gait3D/Gait3D-Benchmark/blob/72beab994c137b902d826f4b9f9e95b107bebd78/misc/pretreatment_smpl.py#L45) is the code for generating smpl.pkl. We sorted it by [time/file_name order](https://github.com/Gait3D/Gait3D-Benchmark/blob/72beab994c137b902d826f4b9f9e95b107bebd78/misc/pretreatment_smpl.py#L37).

**Comment by yan811** [comment]
Thanks for your kind and quick reply! I'll take a closer look.
