### ISSUE TITLE
question about iteration and epoch

### ISSUE THREAD

**Issue by yan811** [Gait3D/Gait3D-Benchmark#13]
Hi!
The total iteration in your code is set to 180000, and you report the total epoch as 1200 in your paper. 
What's the relationship between iteration and epoch?

**Comment by JinkaiZheng** [comment]
Trainset has 18940 sequences
Batch size = 32 * 4 = 128 sequences
One epoch = 18940 / 128 ≈ 150 iterations
So, 180,000 iterations = 1200 * 150 ≈ 1200 epochs

**Comment by yan811** [comment]
Thanks!
