### ISSUE TITLE
about heatMap in Fig.6 ("Gait Recognition in the Wild with Multi-hop Temporal Switch")

### ISSUE THREAD

**Issue by Au21ke** [Gait3D/Gait3D-Benchmark#17]
Sorry to bother you, can you briefly share how you got the gait heatmap?

**Comment by JinkaiZheng** [comment]
Hi~ You can output one layer from the network directly, let's say X1. 
Then, use ` cv2.resize` to resize X1 to X2 (size: 64x44). 
Finally, employ `cv2.applyColorMap(X2, cv2.COLORMAP JET)` to get the heatmap.
