### ISSUE TITLE
5.1.2 Model-based Approaches

### ISSUE THREAD

**Issue by lihuiGZHU** [Gait3D/Gait3D-Benchmark#18]
I have a few questions about model-based methods which use 3D skeletons as the input.
1.Does your code reflect the use of posegait to train 3Dskeleton data？
2.The 3D skeleton data in Gait3D is under which folder in your data？

**Comment by JinkaiZheng** [comment]
Hi~ Thank you for your question. 
1. We reproduce PoseGait based on the description of the PoseGait paper, combined with the partial code published by the author (https://github.com/RijunLiao/PoseGait)
2. The 3D skeleton data in Gait3D is under `3D SMPLs NPZ`. Specifically, the 3D skeleton used in our paper is **j3d_smpl24** in 3D SMPL NPZ.

**Comment by lihuiGZHU** [comment]
Thank you for your reply！

**Comment by lihuiGZHU** [comment]
I also want to ask you a question, do you have a backup of the code for reproducing posegait using Gait3D's 3Dskeleton data as input, and if so, can you send me a copy, because it will greatly reduce my workload. This is my email lihui0627@e.gzhu.edu.cn, thank you very much! ! !

**Comment by JinkaiZheng** [comment]
I'm sure you'll be able to do it yourself as described in the PoseGait paper, and it won't take you too much time, so good luck.
