### ISSUE TITLE
Questions about the mtsgait model

### ISSUE THREAD

**Issue by cj271** [Gait3D/Gait3D-Benchmark#22]
Sorry to bother you.   
in mtsgait.py，I can't find the code of the "Spatial and Temporal Feature Extractor" module in Figure 2 in the paper , Where can I get the code for this part?

**Comment by JinkaiZheng** [comment]
Hi~ The code you want is at [here](https://github.com/Gait3D/Gait3D-Benchmark/blob/9baa0255a5d58e3dbffc269ac84407ab4cac8269/opengait/modeling/modules.py#L137).

**Comment by cj271** [comment]
thank u very much!
