### ISSUE TITLE
config

### ISSUE THREAD

**Issue by Lxzzzzzzzzzzz** [Gait3D/Gait3D-Benchmark#23]
what is the different between smplgait.yaml and smplgait_gait3d.yaml?why need two?

**Comment by JinkaiZheng** [comment]
Hi~ Thank you for your inquiry.
The "smplgait.yaml" is the configuration file replicated by the OpenGait Team, while the "smplgait_gait3d.yaml" is the configuration used in our original research paper.

**Comment by Lxzzzzzzzzzzz** [comment]
Thank you for your reply! I also want to know if i want to recurrent the result in your original research paper result ,  should i just change  data_in_use: [false, true, true] to [true, true] in the smplgait_gait3d.yaml?

**Comment by JinkaiZheng** [comment]
You can use smplgait_gait3d.yaml directly without modifying any configuration.

**Comment by Lxzzzzzzzzzzz** [comment]
Thank you for your reply!
But i just use "python datasets/Gait3D/merge_two_modality.py --sils_path 'Gait3D-sils-64-64-pkl' --smpls_path 'Gait3D-smpls-pkl' --output_path 'Gait3D-merged-pkl' --link 'hard' " instead of " python datasets/Gait3D/merge_three_modality.py --pars_path 'Gait3D-pars-64-64-pkl' --sils_path 'Gait3D-sils-64-64-pkl' --smpls_path 'Gait3D-smpls-pkl' --output_path 'Gait3D-merged-pkl' --link 'hard' ".
So if i want to recurrent the result in your original research paper result , should i just change data_in_use: [false, true, true] to [true, true] in the smplgait_gait3d.yaml?

**Comment by JinkaiZheng** [comment]
Yes
