### ISSUE TITLE
How to visualize smpl data

### ISSUE THREAD

**Issue by faiimea** [Gait3D/Gait3D-Benchmark#26]
I am trying to visualize an SMPL file like human_crop_xxxxx.npz in the 3D_SMPLS folder back to a picture with a human. And I noticed that you showed pictures of visualizing SMPL data on your home page, and I was wondering if there is any way to convert the current npz data into pictures with portraits.
I will appreciate if you could provide any help. :p

**Comment by JinkaiZheng** [comment]
Hi, please refer to this [repo](https://github.com/Arthur151/ROMP).
