### ISSUE TITLE
why we need a identity matrix ?

### ISSUE THREAD

**Issue by HiAleeYang** [Gait3D/Gait3D-Benchmark#5]
https://github.com/Gait3D/Gait3D-Benchmark/blob/72beab994c137b902d826f4b9f9e95b107bebd78/lib/modeling/models/smplgait.py#L55

**Comment by JinkaiZheng** [comment]
Hi~ Since we are using matrix multiplication, the identity matrix here is equal to the element-wise sum in our framework.
