### ISSUE TITLE
GREW pretreatment `to_pickle` has size 0

### ISSUE THREAD

**Issue by gosiqueira** [Gait3D/Gait3D-Benchmark#6]
I'm trying to run GREW pretreatment code but it generates no `GREW-pkl` folder at the end of the process.
I debugged myself and checked if the `--dataset` flag is set properly and the `to_pickle` list size before saving the pickle file.
The flag is well set but the size of the list is always 0.

I downloaded the GREW dataset from the link you guys sent me and made de `GREW-rearranged ` folder using the code provided.
I'll keep investigating what is causing such an error and if I find I'll set a fixing PR.

**Comment by JinkaiZheng** [comment]
Hi~ I guess you are using the newer [OpneGait](https://github.com/ShiqiYu/OpenGait) code. 
If you want to run GREW successfully, you have two options:
1) Please download the source code for this [repo](https://github.com/Gait3D/Gait3D-Benchmark) and run `sh misc/run_pretreatment_grew.sh` with **the original directory structure** that GREW decompressed.
Then,  please refer to the [train ](https://github.com/Gait3D/Gait3D-Benchmark/blob/main/train.sh)/[test ](https://github.com/Gait3D/Gait3D-Benchmark/blob/main/test.sh)file and rewrite the command as follows:
For training: 
`CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 lib/main.py --cfgs ./config/gaitset_64pixel_GREW_office_split.yaml --phase train`
For testing: 
`CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 lib/main.py --cfgs ./config/gaitset_64pixel_GREW_office_split.yaml --phase test`
In addition, you can change the config file to `gaitset_64pixel_GREW_our_split.yaml` to implement localization testing, as used in our [paper](https://arxiv.org/abs/2204.02569).
2) Download the latest [OpneGait](https://github.com/ShiqiYu/OpenGait) source code and follow their [tutorial](https://github.com/ShiqiYu/OpenGait/tree/master/datasets/GREW#grew-tutorial).
