### ISSUE TITLE
ROMP SMPL transfer

### ISSUE THREAD

**Issue by ThomasNing** [Gait3D/Gait3D-Benchmark#8]
When I try to use the ROMP to generate out the 3D mesh, I detect there is a version conflict with the ROMP used by SMPLGait. Could I know which version of the ROMP the SMPLGait used? In this way I could use the SMPLGait to run on other ReID dataset.

**Comment by Gait3D** [comment]
Dear Thomas,
    The version of ROMP we used is V1.0, but the latest version should be
compatible.


Best regards,
The group of Gait3D

Thomas Ning ***@***.***> 于2022年8月2日周二 13:40写道：

**Comment by ThomasNing** [comment]
I use the latest version of the ROMP. Unfortunately, the ROMP team changes their .npz data output format, with different names of the result and also the matrix shape size of the poses. So the preprocess_smpl.py document failed to preprocess the latest romp output. What I can do is to modify the preprocess code to align the new format of the romp output.

**Comment by JinkaiZheng** [comment]
Okay, good luck!

**Comment by ZziTaiLeo** [comment]
> I use the latest version of the ROMP. Unfortunately, the ROMP team changes their .npz data output format, with different names of the result and also the matrix shape size of the poses. So the preprocess_smpl.py document failed to preprocess the latest romp output. What I can do is to modify the preprocess code to align the new format of the romp output.

Have you solved the problem?  Can you share the code of data preprocessing after ROMP.
